dataset: "LJSpeech"

path:
  corpus_path: "./datasets"
  preprocessed_path: "./preprocessed_data/SingleSpk"

preprocessing:
  sanity_check: False # if Ture, then preprocess a single data and quit
  val_size: 512
  text:
    text_cleaners: ["english_cleaners"]
    language: "en"
  audio:
    sampling_rate: 44100
    max_wav_value: 32768.0
    skip_len: 14848
    trim_top_db: 23
    silence_audio_size: 5
    pre_emphasis: False
  stft:
    filter_length: 2048
    hop_length: 512
    win_length: 2048
  mel:
    n_mel_channels: 80
    mel_fmin: 20
    mel_fmax: 11025 # please set to 8000 for HiFi-GAN vocoder, set to null for MelGAN vocoder
    normalize: False
